### ISSUE TITLE
Some BOOT files identified as BLOAD

### ISSUE THREAD

**Issue by ChoccyHobNob** [robmcmullen/atrcopy#7]
Sorry for all these bug reports :/ 

These files are bootable but atrcopy is saying they are BLOAD. For the looks of it they are some kind of tape to disk software so may be mostly just a bunch of binary but there is a bootable bit in there somewhere!

[bootable bloads.zip](https://github.com/robmcmullen/atrcopy/files/1347245/bootable.bloads.zip)

**Comment by robmcmullen** [comment]
Keep 'em coming, it's great to seeing this being used.

**Comment by robmcmullen** [comment]
They are definitely unusual, but they boot. The 007 loads 2 sectors at $0080 atd $0100 (the bottom of the stack!) and goes about its boot process.

I don't know how I'm going to ID these files... I guess I know that they are ATR images, so once I know that, just default to a boot disk if I can't parse it otherwise.

**Comment by robmcmullen** [comment]
OK, try version 6.2 from pip and see if that works on more of your examples.

**Comment by ChoccyHobNob** [comment]
Once I remove any disk marked as greater than disk 1 or side a, then remove all the ones that crash the emulator for some reason (there are a worrying number of those), and all the ones atrcopy now sees as bootable; all that is left is three different versions of the attached file. 
[Abraxas-Assault On The Astral Rift A[BSave].ATR.zip](https://github.com/robmcmullen/atrcopy/files/1350052/Abraxas-Assault.On.The.Astral.Rift.A.BSave.ATR.zip)

BSave is now gone? you are marking them all as unidentified contents.

**Comment by robmcmullen** [comment]
BSAVE is actually an Apple II executable format which is why it's not defaulting to that.

This particular disk image is weird, it has tries to load 10 sectors in the boot process, but starts at address b880, which means it tries to read the last sector into c000-c07f, which is ROM. My validation check is that no boot sectors are read into ROM, which in general I think is the proper check. I think this is just a really weird disk.

**Comment by ChoccyHobNob** [comment]
I thought that was just your name for "bunch of binary data saved to disk for loading by another program" It's usually side/disk 2 of a game/app that was being identified as bsave and I'd say that's mostly correct.

Maybe ident as NDOS/NBOOT? 

I have a few like this file, 
[DOS Control v1.3 (2000-12-12)(Dial)(pl)[a][BSave].atr.zip](https://github.com/robmcmullen/atrcopy/files/1350145/DOS.Control.v1.3.2000-12-12.Dial.pl.a.BSave.atr.zip) which is obviously trying to boot but not making it.
